Repository qin-team-recipe/02-recipe-api, pull requests merged in 2023-06, with the labels that each got.

#7 feature/add chef api
  cmd/app/main.go
  internal/domain/.gitkeep
  internal/domain/chefs.go
  internal/infrastructure/routing.go
  internal/interface/controllers/.gitkeep
  internal/interface/controllers/context.go
  internal/interface/controllers/product/chefs_controller.go
  internal/interface/gateways/db.go
  internal/interface/gateways/db_gateways.go
  internal/interface/gateways/repository/.gitkeep
  internal/interface/gateways/repository/chef_repository.go
  internal/usecase/gateway/db_gateway.go
  internal/usecase/interactor/.gitkeep
  internal/usecase/interactor/product/chef_interactor.go
  internal/usecase/repository/.gitkeep
  internal/usecase/repository/chef_repository.go
Labels: Type:new feature

#11 feature/add recipe api
  app/internal/domain/recipes.go
  app/internal/infrastructure/routing.go
  app/internal/interface/controllers/product/recipes_controller.go
  app/internal/interface/gateways/repository/recipe_repository.go
  app/internal/usecase/interactor/product/recipe_interactor.go
  app/internal/usecase/repository/recipe_repository.go
Labels: Priority:high, Type:new feature

#22 swaggerドキュメントの整備
  app/docs/docs.go
  app/docs/swagger.json
  app/docs/swagger.yaml
  app/internal/infrastructure/routing.go
  app/internal/interface/controllers/product/chef_follows_controller.go
  app/internal/interface/controllers/product/chef_recipes_controller.go
  app/internal/interface/controllers/product/chefs_controller.go
  app/internal/interface/controllers/product/recipe_favorites_controller.go
  app/internal/interface/controllers/product/recipe_ingredients_controller.go
  app/internal/interface/controllers/product/recipe_links_controller.go
  app/internal/interface/controllers/product/recipe_steps_controller.go
  app/internal/interface/controllers/product/shopping_items_controller.go
  app/internal/interface/controllers/product/user_recipes_controller.go
  app/internal/interface/controllers/product/user_shopping_items_controller.go
  app/internal/interface/controllers/product/users_controller.go
Labels: Type:improvement, Type:design
